- name: "Voice Over Bootcamp"
  institution: "Six Degrees/Christian Goutsis"
- name: "Television and Radio Production (including Voice, Writing, Directing)"
  institution: "Wheaton Collage Graduate School, MA in Communications"
- name: "Television, Stage and Theatre Arts (including Acting, Voice,	Writing)"
  institution: "Southern Alberta Institute of Technology"
- name: "Acting Workshops"
  institution: "Ambrose University"
- name: "Theatre Arts Workshops (Acting, Movement, Stage Fighting,	Scene Study, Audition, Playwriting, Directing)"
  institution: "Prarie Collage"

